<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
$verticalMenu = $helper->getConfig('themelayoutpro/header/vertical_menu');
$title = $helper->getConfig('themelayoutpro/header/vertical_menu_title');
?>

<?php if ($verticalMenu) : ?>
<div id="desk_vertcial-menu-container" class="hidden-xs desk-vertcial-menu-container">
    <div class="main-content-top-left" data-role="menu-container">
        <div class="menu-title" data-role="menu-title"><?= $title ?></div>
        <div class="menu-container hidden-xs" data-role="menu-content">
            <?php echo $this->getLayout()->createBlock('Codazon\MegaMenu\Block\Widget\Megamenu')->setMenu($verticalMenu)->setType(1)->toHtml(); ?>
        </div>
    </div>
</div>
<?php endif ?>