<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_ReCaptcha
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block MSP\ReCaptcha\Block\Frontend\ReCaptcha */
?>
<?php
$oldId = $block->getRecaptchaId()? : "msp-recaptcha";
$uniqid = $this->getCustomRecaptchaId() ? : ($block->getRecaptchaId()? : "msp-recaptcha-".uniqid());
$config = json_decode($block->getJsLayout(), true);
if (isset($config['components'][$oldId]) && $this->getCustomRecaptchaId()) {
    $config['components'][$uniqid] = $config['components'][$oldId];
    unset($config['components'][$oldId]);
    $config['components'][$uniqid]['reCaptchaId'] = $uniqid;
}
?>
<?php if (!empty($config['components'][$uniqid]['settings'])) : ?>
<div class="field-recaptcha" id="<?= $uniqid ?>-container" data-bind="scope:'<?= $uniqid ?>'" data-mage-init='{"Magento_Ui/js/core/app": <?= json_encode($config) ?>}'>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<?php endif ?>