<?php
/**
 * Copyright © 2018 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* $block Codazon\ShoppingCartPro\Block\MiniCart */
?>

<div class="footer-minicart" id="cdz-footer-minicart" data-block='minicartpro' style="display: none;">
    <div class="footer-cart-inner" data-bind="scope: 'minicartpro_content'">
        <a class="cart-trigger" data-role="cart-trigger">
            <span class="flying-destination" data-role="flying-destination"></span>
            <span class="summary-count-label" data-role="cart-count">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                    <!-- ko i18n: 'items in your cart' --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('summary_count') -->
                    <!-- ko i18n: 'Your cart is empty' --><!-- /ko -->
                <!-- /ko -->
            </span>
            <span class="proccessing-label" data-role="cart-processing" style="display: none;">
                 <!-- ko i18n: 'Proccessing...' --><!-- /ko -->
            </span>
        </a>
        <div class="block-minicartpro" data-role="cart-content" style="display: none;">
            <div id="minicartpro-content-wrapper">
                <!-- ko template: 'Codazon_ShoppingCartPro/minicart/content-footer.html' --><!-- /ko -->
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
	"[data-block='minicartpro']": {
		"Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
	}
}
</script>