<?php
/**
 * Copyright © 2018 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* $block Codazon\ShoppingCartPro\Block\MiniCart */
?>

<div class="sidebar-minicart" id="cdz-sidebar-minicart" data-block='minicartpro'>
    <div class="cdz-backface" data-action="close"></div>
    <div class="sidebar-cart-inner" data-bind="scope: 'minicartpro_content'">
        <a class="cart-trigger" data-role="cart-trigger">
            <span class="flying-destination" data-role="flying-destination"></span>
            <span class="summary-count-label" data-role="cart-count">
                <!-- ko if: getCartParam('summary_count') -->
                    <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- /ko -->
                <!-- ko ifnot: getCartParam('summary_count') -->
                    <!-- ko i18n: '0' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </a>
        <div class="block-minicartpro block-minicart" data-role="cart-content">
            <div id="minicartpro-content-wrapper">
                <!-- ko template: 'Codazon_ShoppingCartPro/minicart/content-sidebar.html' --><!-- /ko -->
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
	"[data-block='minicartpro']": {
		"Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
	}
}
</script>