<?php
/**
 *
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$pageUrl = $this->getData('page_url');
$hideCover = (int)$this->getData('hide_cover');
$showFacepile = (int)$this->getData('show_facepile');
?>

<div id="fb-root"></div>
<script type='text/javascript'>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=525188320996791";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<div class="fb-page" 
	data-href="<?= $pageUrl ?>" 	
	data-small-header="false"
	data-adapt-container-width="true"
	data-hide-cover="<?php echo $hideCover ?>"
	data-show-facepile="<?php echo $showFacepile ?>">
	<div class="fb-xfbml-parse-ignore">
		<blockquote cite="<?= $pageUrl ?>">
			<a href="<?= $pageUrl ?>">Facebook</a>
		</blockquote>
	</div>
</div>