<?php
/**
 * Copyright © 2018 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php $_product = $block->getProduct(); ?>
<?php if (!$block->hasOptions()):?>
    <?php echo $block->getChildHtml('product_info_form_content'); ?>
<?php else:?>
    <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
        <?php echo $block->getChildChildHtml('options_container') ?>
    <?php endif;?>
<?php endif; ?>
<?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
    <?php echo $block->getChildChildHtml('options_container') ?>
<?php endif;?>