<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<div class="block account-nav" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "account-nav-active", "element": "body" } }}'>
    <div class="title">
        <strong data-role="title"><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?= $block->getChildHtml() ?>
            </ul>
        </nav>
    </div>
</div>
